version: "2.1"

services:
  checkmk_exporter:
    image: thachnv92/checkmk_exporter:1.1
    restart: unless-stopped
    net: host
    environment:
      CHECKMK_HOSTNAME: "checkmk.example.com"
      CHECKMK_DASHBOARD: "site_name"
      CHECKMK_USERNAME: "automation"
      CHECKMK_SECRET: "your_secret_here"
      CHECKMK_VIEW_NAME: "allhosts"
      CHECKMK_SERVER_PORT: "9293"
      CHECKMK_METRIC_NAME: "checkmk_status"
      SERVERS_CSV_PATH: "/servers.csv"
    ports:
      - "9293:9293"
    read_only: true
    volumes:
      - ./servers.csv:/servers.csv:ro
